# Generated by Django 4.2.4 on 2023-09-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='owner',
        ),
    ]
